//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freescape.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingInterior
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuildingInterior()
        {
            this.ConstructionSites = new HashSet<ConstructionSite>();
            this.PCTerritoryFlagsStructures = new HashSet<PCTerritoryFlagsStructure>();
        }
    
        public int BuildingInteriorID { get; set; }
        public int BuildingCategoryID { get; set; }
        public string AreaResref { get; set; }
        public string Name { get; set; }
        public bool IsDefaultForCategory { get; set; }
    
        public virtual BuildingCategory BuildingCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionSite> ConstructionSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCTerritoryFlagsStructure> PCTerritoryFlagsStructures { get; set; }
    }
}
