//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freescape.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionSiteComponent
    {
        public int ConstructionSiteComponentID { get; set; }
        public int ConstructionSiteID { get; set; }
        public int Quantity { get; set; }
        public int StructureComponentID { get; set; }
    
        public virtual ConstructionSite ConstructionSite { get; set; }
        public virtual StructureComponent StructureComponent { get; set; }
    }
}
