//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freescape.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CraftBlueprint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CraftBlueprint()
        {
            this.CraftBlueprintComponents = new HashSet<CraftBlueprintComponent>();
        }
    
        public long CraftBlueprintID { get; set; }
        public long CraftCategoryID { get; set; }
        public int Level { get; set; }
        public string ItemName { get; set; }
        public string ItemResref { get; set; }
        public int Quantity { get; set; }
        public int SkillID { get; set; }
        public int CraftDeviceID { get; set; }
        public Nullable<int> PerkID { get; set; }
        public int RequiredPerkLevel { get; set; }
        public bool IsActive { get; set; }
        public int CraftTierLevel { get; set; }
    
        public virtual CraftBlueprintCategory CraftBlueprintCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CraftBlueprintComponent> CraftBlueprintComponents { get; set; }
        public virtual CraftDevice CraftDevice { get; set; }
        public virtual Perk Perk { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
