//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freescape.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrowingPlant
    {
        public int GrowingPlantID { get; set; }
        public int PlantID { get; set; }
        public int RemainingTicks { get; set; }
        public string LocationAreaTag { get; set; }
        public string LocationX { get; set; }
        public string LocationY { get; set; }
        public string LocationZ { get; set; }
        public string LocationOrientation { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public int TotalTicks { get; set; }
        public int WaterStatus { get; set; }
        public int LongevityBonus { get; set; }
    
        public virtual Plant Plant { get; set; }
    }
}
