//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freescape.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCCorpseItem
    {
        public long PCCorpseItemID { get; set; }
        public long PCCorpseID { get; set; }
        public byte[] NWItemObject { get; set; }
    
        public virtual PCCorps PCCorps { get; set; }
    }
}
