//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freescape.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCOutfit
    {
        public string PlayerID { get; set; }
        public byte[] Outfit1 { get; set; }
        public byte[] Outfit2 { get; set; }
        public byte[] Outfit3 { get; set; }
        public byte[] Outfit4 { get; set; }
        public byte[] Outfit5 { get; set; }
        public byte[] Outfit6 { get; set; }
        public byte[] Outfit7 { get; set; }
        public byte[] Outfit8 { get; set; }
        public byte[] Outfit9 { get; set; }
        public byte[] Outfit10 { get; set; }
    
        public virtual PlayerCharacter PlayerCharacter { get; set; }
    }
}
