//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freescape.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCTerritoryFlagsStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PCTerritoryFlagsStructure()
        {
            this.PCTerritoryFlags = new HashSet<PCTerritoryFlag>();
            this.PCTerritoryFlagsStructuresItems = new HashSet<PCTerritoryFlagsStructuresItem>();
            this.StructureQuickBuildAudits = new HashSet<StructureQuickBuildAudit>();
        }
    
        public long PCTerritoryFlagStructureID { get; set; }
        public int PCTerritoryFlagID { get; set; }
        public int StructureBlueprintID { get; set; }
        public bool IsUseable { get; set; }
        public string LocationAreaTag { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public double LocationZ { get; set; }
        public double LocationOrientation { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CustomName { get; set; }
        public Nullable<int> BuildingInteriorID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BuildingInterior BuildingInterior { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCTerritoryFlag> PCTerritoryFlags { get; set; }
        public virtual PCTerritoryFlag PCTerritoryFlag { get; set; }
        public virtual StructureBlueprint StructureBlueprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCTerritoryFlagsStructuresItem> PCTerritoryFlagsStructuresItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StructureQuickBuildAudit> StructureQuickBuildAudits { get; set; }
    }
}
