//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freescape.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCTerritoryFlagsPermission
    {
        public int PCTerritoryFlagPermissionID { get; set; }
        public int PCTerritoryFlagID { get; set; }
        public string PlayerID { get; set; }
        public int TerritoryFlagPermissionID { get; set; }
    
        public virtual PCTerritoryFlag PCTerritoryFlag { get; set; }
        public virtual PlayerCharacter PlayerCharacter { get; set; }
        public virtual TerritoryFlagPermission TerritoryFlagPermission { get; set; }
    }
}
