//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freescape.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCTerritoryFlag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PCTerritoryFlag()
        {
            this.ConstructionSites = new HashSet<ConstructionSite>();
            this.PCTerritoryFlagsPermissions = new HashSet<PCTerritoryFlagsPermission>();
            this.PCTerritoryFlagsStructures = new HashSet<PCTerritoryFlagsStructure>();
            this.StructureQuickBuildAudits = new HashSet<StructureQuickBuildAudit>();
        }
    
        public int PCTerritoryFlagID { get; set; }
        public string PlayerID { get; set; }
        public int StructureBlueprintID { get; set; }
        public string LocationAreaTag { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public double LocationZ { get; set; }
        public double LocationOrientation { get; set; }
        public int BuildPrivacySettingID { get; set; }
        public bool ShowOwnerName { get; set; }
        public Nullable<long> BuildingPCStructureID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BuildPrivacyDomain BuildPrivacyDomain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionSite> ConstructionSites { get; set; }
        public virtual PCTerritoryFlagsStructure PCTerritoryFlagsStructure { get; set; }
        public virtual PlayerCharacter PlayerCharacter { get; set; }
        public virtual StructureBlueprint StructureBlueprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCTerritoryFlagsPermission> PCTerritoryFlagsPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCTerritoryFlagsStructure> PCTerritoryFlagsStructures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StructureQuickBuildAudit> StructureQuickBuildAudits { get; set; }
    }
}
